controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller   
    type: attribute

   # candidats:
       # path: /Candidats
       # controller: App\Controller\Candidats\CandidatsController::index

        
        
        
